hotel-reverse/hotel-reverse

app.js, bin/www, package.json, public/stylesheets/style.css, routes/index.js, routes/users.js, views/error.jade, views/index.jade, views/layout.jade, webpack.config.js
=> (feat) Done initial server setting

.travis.yml
#7
initial travis setting to test and deploy
=> (feat) Done initial travis setting to test and deploy

schema.sql
=> (feat) Added schema

server/config/middleware.js, server/config/routes.js, server/controllers/index.js, server/db/index.js, server/server.js, server/webpack.config.js
feat/server: setup server
feat/middleware: setup middleware
feat/routes: setup routes
feat/DB-connection: setup DB connection
feat/controllers: setup controllers
feat/helpers: create empty helpers.js file
feat/webpack.config.js: copied from previous project(react)
=> Feat/Set Node Server

server/config/routes.js, server/controllers/index.js
#2 
Controllers
- Client
- signUp, signIn, getAllContracts, getContract, makeContract, updateInfo
- cancelContract, makeFeedback(pending)
- Hotel
- signUp, signIn, bidInfo, bidInfoInterval, update
- bid(pending)
routes
- update verbs
=> (feat) Updated controllers and routes

server/config/routes.js, server/controllers/index.js
Contorllers
- tested SQL in mysql command line
- updated method name: user-> client, manager-> hotel
- avoided async problem: (second query only executed after first query ended)
Routes
- changed method name
=> (feat) Updated routes and controllers

server/package.json, server/src/config/routes.js, server/src/controllers/index.js
controllers/index.js
- changed SQL query: from string concatenation into positional indicator
- meant ? indicator for values instead of string concatenation
config/routes.js
- uncommented tested routes
=> (controllers) Tested controllers, uncommented tested routes

HotelAndroid/android/HotelAndroid.iml, HotelAndroid/android/app/app.iml, HotelAndroid/android/app/build.gradle, HotelAndroid/android/app/src/main/AndroidManifest.xml, HotelAndroid/android/app/src/main/res/values/strings.xml, HotelAndroid/android/build.gradle, HotelAndroid/check.js, HotelAndroid/hotelBid.js, HotelAndroid/hotelSearch.js, HotelAndroid/hotelSignin.js, HotelAndroid/index.android.js, HotelAndroid/login.js, HotelAndroid/package.json, HotelAndroid/register.js
1. Bid to enter the Subarea, price
2. Login to check login or skip it
3. Register to be the member
=> (feat)Added the client page - bid, login, register

HotelAndroid/hotelBid.js, HotelAndroid/hotelSearch.js, HotelAndroid/index.android.js, HotelAndroid/register.js
- changed state data into 3 objects in index.android.js
- fixed few words in hotelBind.js and hotelSearch.js
=> (refactor) changed state data

HotelAndroid/getLatestBidInfo.js, HotelAndroid/hotelBid.js, HotelAndroid/hotelSearch.js, HotelAndroid/hotelSignin.js, HotelAndroid/index.android.js
getLatestBidInfo.js
- Received state from bid
- Send transaction to the DB
hotelBid.js
- Changed variable names into database field name
hotelSearch.js
- Changed variable names into database field name
- Changed date format into YYYY-MM-DD
=> (feat/confirm-deal) Tested state transfer between modules

server/gulpfile.js, server/package.json, server/specs/server/clientControllerSpec.js, server/src/config/init.js
=> test/Added supertest+mocha tests

HotelAndroid/hotelBid.js, HotelAndroid/hotelSearch.js, HotelAndroid/index.android.js
- divided subArea_Name depending on mainArea_Name
- index.android.js: added searchData in bid rendering side
- hotelBid.js: added division of subArea_Name
- additionally, fix value of mainArea_Name in rendering side
=> (refactor) divided subArea_Name

server/src/config/routes.js, server/src/controllers/adminController.js, server/src/controllers/hotelController.js, server/src/db/index.js
- Added comments to routes.js
- Remove comments from hotelController.js
- Remove comments from adminController.js
=> (feat/confirm-deal) Added comments to routes.js 

HotelAndroid/hotelBid.js
- added key in Item template in rows
(reference)
http://stackoverflow.com/questions/28329382/understanding-unique-keys-for-array-children-in-react-js
=> (refacotr) fixed error in hotelBid

HotelAndroid/hotelSignin.js, HotelAndroid/register.js, server/package.json, server/src/controllers/clientController.js
Client register connected to db by axios
=> (feat) Connect client register to DB 

schema.sql, server/package.json, server/src/config/init.js, server/src/config/routes.js, server/src/controllers/adminController.js, server/src/controllers/clientController.js, server/src/controllers/hotelController.js, server/src/db/index.js
1. server/src/db/index.js
- Refactored using sequelize ORM
2. server/src/controllers/adminController.js
- Refactored using sequelize ORM and tested all routes
3. server/src/controllers/clientController.js
- Refactored using sequelize ORM and tested all routes
4. server/src/controllers/hotelController.js
- Refactored using sequleize ORM, but not tested all routes
5. server/src/config/routes.js
- Added comments
6. server/package.json
- Added sequelize and moment
* npm install sequelize --save
* npm install moment --save
7. schema.sql (by NY)
- Modified schema
* added hotel_ID field in Deal Table
* remove booking_Num field in Hotel Table
* hotel_ID is no longer a foreign key in Deal Table
8. init.js (by NY)
- Modified according to changed schema
=> (refactor/db) Refactored mysql raw queries into sequelize ORM

HotelAndroid/android/app/build.gradle, HotelAndroid/android/app/google-services.json, HotelAndroid/android/app/src/main/java/com/hotelandroid/MainActivity.java, HotelAndroid/android/build.gradle, HotelAndroid/android/gradle/wrapper/gradle-wrapper.properties, HotelAndroid/android/settings.gradle, HotelAndroid/hotelSignin.js, HotelAndroid/package.json
Add google login to hotelSignin.js page by 'react-native-google-signin'
** USE react-native-google-signin **
[android-guide] https://github.com/devfd/react-native-google-signin/blob/master/android-guide.md
[example] https://github.com/devfd/react-native-google-signin/blob/master/example/index.android.js
[How to get the GoogleClientID]
=> (feat) Added the google login function

server/gulpfile.js, server/src/config/init.js, server/src/config/middleware.js, server/src/config/routes.js, server/src/controllers/adminController.js, server/src/controllers/clientController.js, server/src/controllers/dealController.js, server/src/controllers/hotelController.js, server/src/db/index.js, server/src/server.js, server/webpack.config.js
resolve #63
1. var -> const / let
- const : the identifier can’t be reassigned.
- let : the variable may be reassigned
2. function(a, b) { } -> (a,b) => { }
Reference : http://babeljs.io/docs/learn-es2015/
=> (Refactor) Modified server files es5 to es6

HotelAndroid/getLatestBidInfo.js, server/src/config/routes.js, server/src/controllers/clientController.js, server/src/controllers/dealController.js, server/src/db/index.js
Reverts hotel-reverse/hotel-reverse#84
=> Revert "Feat/add payment"

HotelAndroid/getLatestBidInfo.js
- Can`t submit when input is invalidate
=> (fix) Fix bug in submit in getLatestBidInfo.js

server/src/config/init.js
Changed the order insertion
Removed setTimeout()
=> (refactor/init) Modified init.js

server/admin/app/services/clients.service.ts, server/admin/app/services/contracts.service.ts, server/admin/app/services/deals.service.ts, server/admin/app/services/host-url.ts, server/admin/app/services/hotels.service.ts, server/manager/app/services/contracts.service.ts, server/manager/app/services/host-url.ts, server/manager/app/services/sign.service.ts, server/manager/app/services/update.service.ts
- host-url.ts
* Defined hostUrl varialbe that holds amazon host
=> (refactor/angular-url) Changed hard-coded url into a variable

server/package.json, server/src/controllers/clientController.js, server/src/controllers/hotelController.js
https://github.com/ncb000gt/node.bcrypt.js
=> (feat) Hashed the password when signup/signin

server/src/config/init.js
=> Applied encryption in init.js
